/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppStudentsRouteImport } from './routes/_app.students'
import { Route as AppResourcesRouteImport } from './routes/_app.resources'
import { Route as AppMessagesRouteImport } from './routes/_app.messages'
import { Route as AppMarketplaceRouteImport } from './routes/_app.marketplace'
import { Route as AppLessonsRouteImport } from './routes/_app.lessons'
import { Route as AppLeadsRouteImport } from './routes/_app.leads'
import { Route as AppInsightsRouteImport } from './routes/_app.insights'
import { Route as AppFinanceRouteImport } from './routes/_app.finance'
import { Route as AppCommunityRouteImport } from './routes/_app.community'
import { Route as AppCalendarRouteImport } from './routes/_app.calendar'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsRoute = AppStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppRoute,
} as any)
const AppResourcesRoute = AppResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketplaceRoute = AppMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => AppRoute,
} as any)
const AppLessonsRoute = AppLessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityRoute = AppCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/calendar': typeof AppCalendarRoute
  '/community': typeof AppCommunityRoute
  '/finance': typeof AppFinanceRoute
  '/insights': typeof AppInsightsRoute
  '/leads': typeof AppLeadsRoute
  '/lessons': typeof AppLessonsRoute
  '/marketplace': typeof AppMarketplaceRoute
  '/messages': typeof AppMessagesRoute
  '/resources': typeof AppResourcesRoute
  '/students': typeof AppStudentsRoute
}
export interface FileRoutesByTo {
  '/calendar': typeof AppCalendarRoute
  '/community': typeof AppCommunityRoute
  '/finance': typeof AppFinanceRoute
  '/insights': typeof AppInsightsRoute
  '/leads': typeof AppLeadsRoute
  '/lessons': typeof AppLessonsRoute
  '/marketplace': typeof AppMarketplaceRoute
  '/messages': typeof AppMessagesRoute
  '/resources': typeof AppResourcesRoute
  '/students': typeof AppStudentsRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/community': typeof AppCommunityRoute
  '/_app/finance': typeof AppFinanceRoute
  '/_app/insights': typeof AppInsightsRoute
  '/_app/leads': typeof AppLeadsRoute
  '/_app/lessons': typeof AppLessonsRoute
  '/_app/marketplace': typeof AppMarketplaceRoute
  '/_app/messages': typeof AppMessagesRoute
  '/_app/resources': typeof AppResourcesRoute
  '/_app/students': typeof AppStudentsRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/community'
    | '/finance'
    | '/insights'
    | '/leads'
    | '/lessons'
    | '/marketplace'
    | '/messages'
    | '/resources'
    | '/students'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/calendar'
    | '/community'
    | '/finance'
    | '/insights'
    | '/leads'
    | '/lessons'
    | '/marketplace'
    | '/messages'
    | '/resources'
    | '/students'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/calendar'
    | '/_app/community'
    | '/_app/finance'
    | '/_app/insights'
    | '/_app/leads'
    | '/_app/lessons'
    | '/_app/marketplace'
    | '/_app/messages'
    | '/_app/resources'
    | '/_app/students'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students': {
      id: '/_app/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AppStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resources': {
      id: '/_app/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AppResourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages': {
      id: '/_app/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketplace': {
      id: '/_app/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AppMarketplaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lessons': {
      id: '/_app/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof AppLessonsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads': {
      id: '/_app/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insights': {
      id: '/_app/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance': {
      id: '/_app/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/community': {
      id: '/_app/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AppCommunityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCalendarRoute: typeof AppCalendarRoute
  AppCommunityRoute: typeof AppCommunityRoute
  AppFinanceRoute: typeof AppFinanceRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppLessonsRoute: typeof AppLessonsRoute
  AppMarketplaceRoute: typeof AppMarketplaceRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppResourcesRoute: typeof AppResourcesRoute
  AppStudentsRoute: typeof AppStudentsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalendarRoute: AppCalendarRoute,
  AppCommunityRoute: AppCommunityRoute,
  AppFinanceRoute: AppFinanceRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppLessonsRoute: AppLessonsRoute,
  AppMarketplaceRoute: AppMarketplaceRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppResourcesRoute: AppResourcesRoute,
  AppStudentsRoute: AppStudentsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
